color_palette:
  dark_bg_fore: "#D9D9D9"
  dark_bg_back: "#054062"
items:
  - title: Ahora
    lang: en
    langs:
      - lang: es
        path: /es/
    home: /
    menu:
      - id: home
        label: Plans
        href: /plans/
      - label: FAQs
        href: /faqs/
      - label: Contact
        href: /contact/
  - title: Ahora
    home: /es/
    lang: es
    langs:
      - lang: en
        path: /
    menu:
      - id: home
        label: Plans
        href: /es/plan/
      - label: FAQs
        href: /es/faqs/
      - label: Contact
        href: /es/contact/
